In [133]:
a.shape


(5,)

In [134]:
a.dtype

dtype('int8')

In [135]:
nearray=nu.array([[1,.2,3,4],[5,9,7,3],[7,6,1,8]],dtype=nu.int8)


In [136]:
nearray.size
# nearray.ctypes

12

In [137]:
nearray.dtype
# nearray.round

dtype('int8')

In [138]:

arr = nu.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [139]:
arr=nu.arange(20)

In [140]:
arr=arr.reshape(4,5)

In [141]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [142]:
arr.flat

In [151]:
for i in arr.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [144]:
arr.ndim

2

In [145]:
arr.size

20

In [153]:
arr.nbytes

80

In [152]:
arr.argmax()

19

In [148]:
# arr.argsort()

In [155]:
arr.argmin(axis=1)

array([0, 0, 0, 0], dtype=int64)

In [154]:
arr.argmax(axis=0)


array([3, 3, 3, 3, 3], dtype=int64)

In [157]:
nu.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894]])

In [160]:
nu.count_nonzero(arr)


19

In [161]:
import sys